return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "html-lsp",
      "stimulus-language-server",
      "css-lsp",
      "css-variables-language-server",
      "cssmodules-language-server",
      "biome",
      "stylua",
      "shfmt",
      "yamlfmt",
      "yamllint",
      "markuplint",
      "stylelint",
      "rust-analyzer",
      "pint",
      "emmet-language-server",
      "haml-lint",
      "golangci-lint-langserver",
      "sqls",
    },
  },
}
